# Generated by Django 6.0.2 on 2026-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_photos_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
