# Generated by Django 6.0.2 on 2026-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_product_featured_alter_product_category_order_and_more'),
        ('marketplace', '0008_set_default_category'),
    ]

    operations = [
    ]
