# Generated by Django 6.0.2 on 2026-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_merge_20260403_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
