# Generated by Django 6.0.2 on 2026-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration_verification_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
